# Generated by Django 3.1.7 on 2021-02-24 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('client_id', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID)),
                ('transaction_type', models.CharField(max_length=3)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('intrument', models.CharField(max_length=255)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.broker')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
        ),
    ]
